Fix meta-driver build failure
It failed as the following:

    mongo_wrapper_meta.c: In function ‘MongoConnect’:
    mongo_wrapper_meta.c:73:3: error: unknown type name ‘mongoc_ssl_opt_t’
       mongoc_ssl_opt_t *ssl_opts = (mongoc_ssl_opt_t*) malloc(sizeof(mongoc_ssl_opt_t));
       ^~~~~~~~~~~~~~~~

mongoc_ssl_opt_t is defined in mongoc-ssl.h, but it wasn't included
because we didn't have libssl.